FROM node:18-alpine AS builder
WORKDIR /app

COPY frontend/package.json ./
RUN npm config set registry https://registry.npmmirror.com && npm install -g pnpm && pnpm install

COPY frontend/ ./
RUN pnpm build

FROM nginx:alpine
COPY --from=builder /app/dist /usr/share/nginx/html
COPY frontend/nginx.conf /etc/nginx/conf.d/default.conf
EXPOSE 80
CMD ["nginx", "-g", "daemon off;"]
